version: '3'

services:
  db:
    image: postgis/postgis:13-3.0
    environment:
      - POSTGRES_PASSWORD=onadata
      - POSTGRES_USER=onadata
      - POSTGRES_DB=onadata
    volumes:
      # One level above the code to prevent having to move or delete
      # it everytime we rebuild.
      - ../../../.onadata_db:/var/lib/postgresql/data
  queue:
    image: rabbitmq
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: onadata:latest
    volumes:
      # For local development
      - ../../.:/srv/onadata
    ports:
      - "8000:8000"
    depends_on:
      - db
      - queue
